export type TbProductDto = {
  idx: number
  itemId: string
  barCode: string
  itemSubno: string
  itemName: string
  itemSubname: string
  fileNo: string
  itemSpec: string
  itemPack: string
  itemPacknum: number
  prgOrigin: string
  prdFactory: string
  departCode: string
  vendorId: string
  abc: string
  prdAttrib: string
  manageTpye: string
  classCode: string
  ifInsurance: number
  ifOtc: string
  ifExpensive: number
  ifToxin: number
  purStatus: string
  saleStatus: string
  warningDay: number
  bandCode: string
  state: number
  minUnit: string
  minPrice: number
  itemUnit: string
  salePrice: number
  saleTomin: number
  chkUnit: string
  chkPrice: number
  chkTosale: number
  wholePrice: number
  memPrice: number
  purPrice: number
  realPrice: number
  rebateType: string
  rebate: number
  saleTax: string
  weighType: string
  codeType: string
  createUser: string
  createTime: bigint
  modiNo: string
  lastmodify: number
  codePlant: string
  tradeMark: string
  chemName: string
  chemElement: string
  ecCode: string
  outDepot: string
  costType: string
  electronicCode: string
  robotUnit: string
  synRobot: number
  synMqsta: number
  ifImage: string
  masterImages: string
  detailImages: string
  classCode1: string
  classCode2: string
  specClass: string
  itemUnitDescr: string
  teantId: string
  logicDel: number
}
